- name: Demo on Variables
  hosts: all
  vars:
    URL1: play.google.com
  tasks:
    - name: Print a Variable from Play
      debug:
        msg: URL = {{URL1}}
    - name: Print a varibale from File
      debug:
        msg: URL = {{URL2}}
        