- name: Update Prometheus Config
  template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Prometheus Service
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
