- name: Donwload Node Exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz"
    dest: /opt
    remote_src: yes

- name: Create link of prometheus with standard directory name
  ansible.builtin.file:
    src: /opt/node_exporter-1.2.2.linux-amd64
    dest: /opt/node_exporter
    state: link

- name: Copy SystemD file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start Node exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

