global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#random'
        send_resolved: true
#  - name: email
#    email_configs:
#      - to: raghudevopsb58@gmail.com
#        from: raghudevopsb58@gmail.com
#        smarthost: email-smtp.us-east-1.amazonaws.com:587
#        auth_username: AKIAZHEF5S5CLWR7EGOC
#        auth_password: BPQPL84bzkqGAzfcW50NbOOK2St/b4VXabPbrGawb87t
#        require_tls: yes
#        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
