route:
  group_by: ['alert']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: email
    email_configs:
      - to: raghudevopsb58@gmail.com
        from: raghudevopsb58@gmail.com
        smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: AKIAZHEF5S5CLWR7EGOC
        auth_password: BPQPL84bzkqGAzfcW50NbOOK2St/b4VXabPbrGawb87t
        require_tls: yes
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
