groups:
  - name: HardwareResources
    rules:
      - alert: HighCPU
        expr: cpu_usage_in_percentage > 90
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: HighCPU on {%raw%}{{ $lables.tagName }}{%endraw%}

